version: "3.8"

services:
  db:
    image: postgres:15
    container_name: users-db
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: user-service
    ports:
      - "8083:8083"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
volumes:
  pgdata:
